[package]
name = "rust-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.32"

[[bin]]
name = "gbk2utf8"
path = "gbk2utf8/main.rs"
